/**
 * Tool: local resume storage.
 *
 * Resumes are saved as  <RESUME_STORAGE_DIR>/<id>.pdf
 *   • The id is generated by us (nanoid). The applicant's filename is NEVER
 *     used in the path — that would allow path traversal ("../../etc/passwd").
 *   • The folder lives outside public/, so files are never directly reachable;
 *     admins view them only through GET /api/resumes/[id].
 */
import { createReadStream } from "node:fs";
import { mkdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { getEnv } from "./env";

/** Every real PDF starts with these bytes: "%PDF-". */
const PDF_MAGIC = Buffer.from("%PDF-", "ascii");

export function hasPdfMagicBytes(bytes: Uint8Array): boolean {
  return bytes.length >= PDF_MAGIC.length && PDF_MAGIC.every((b, i) => bytes[i] === b);
}

export type FileCheck = { ok: true } | { ok: false; error: string };

/**
 * Validate an uploaded resume by its CONTENT, not its name or MIME type
 * (both are chosen by the client and trivially faked).
 */
export function validateResumeFile(bytes: Uint8Array, maxMb = getEnv().MAX_RESUME_MB): FileCheck {
  if (bytes.length === 0) return { ok: false, error: "فایل ارسال‌شده خالی است." };
  if (bytes.length > maxMb * 1024 * 1024) {
    return { ok: false, error: `حجم فایل نباید بیشتر از ${maxMb} مگابایت باشد.` };
  }
  if (!hasPdfMagicBytes(bytes)) return { ok: false, error: "فقط فایل PDF معتبر پذیرفته می‌شود." };
  return { ok: true };
}

/** Absolute path of the storage folder. */
function storageDir(): string {
  return path.resolve(process.cwd(), getEnv().RESUME_STORAGE_DIR);
}

/** Save the PDF as <id>.pdf. Returns the path to store in the sheet (relative to the project). */
export async function saveResume(id: string, bytes: Uint8Array): Promise<string> {
  if (!/^[\w-]+$/.test(id)) throw new Error("invalid resume id");
  const dir = storageDir();
  await mkdir(dir, { recursive: true }); // create the folder on first use
  const absolute = path.join(dir, `${id}.pdf`);
  try {
    await writeFile(absolute, bytes, { flag: "wx" }); // "wx": never overwrite an existing file
  } catch (err) {
    // A failed write can leave an empty/partial file behind — remove it.
    if ((err as NodeJS.ErrnoException).code !== "EEXIST") await unlink(absolute).catch(() => undefined);
    throw err;
  }
  return path.relative(process.cwd(), absolute).split(path.sep).join("/");
}

/**
 * Resolve a stored path and make sure it really points inside the storage
 * folder — even though paths come from our own sheet, never trust them blindly.
 */
function resolveInsideStorage(storedPath: string): string {
  const absolute = path.resolve(process.cwd(), storedPath);
  const dir = storageDir();
  if (!absolute.startsWith(dir + path.sep)) throw new Error("resume path is outside the storage folder");
  return absolute;
}

/** Open a stored resume as a web ReadableStream (for streaming to the browser). */
export async function openResume(storedPath: string): Promise<{ stream: ReadableStream; size: number } | null> {
  const absolute = resolveInsideStorage(storedPath);
  const info = await stat(absolute).catch(() => null);
  if (!info?.isFile()) return null;
  return { stream: Readable.toWeb(createReadStream(absolute)) as ReadableStream, size: info.size };
}

/** Remove a stored resume (used to clean up when saving the sheet row fails). */
export async function deleteResume(storedPath: string): Promise<void> {
  await unlink(resolveInsideStorage(storedPath)).catch(() => undefined);
}
